### ISSUE TITLE
Background not changing 

### ISSUE THREAD

**Issue by NulledKebab** [ZesilinaNewborn/midnight-mars#1]
Background color isn't changing
![Screenshot_20211129-142553_Aliucord](https://user-images.githubusercontent.com/70459414/143867902-076a62cb-dc9b-4a92-8763-ebff11da9be4.png)

**Comment by ZesilinaNewborn** [comment]
What's your phone model and which transparency setting are you using? (Sorry for late reply, been busy irl)
